spring.application.name=AI-Powered-Study-Resource-Generator

# Ai
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tornvodutta@gmail.com
spring.mail.password=tqal qdfj htsp grit
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.from=tornovdutta@gmail.com

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Tornov@#129
spring.datasource.url=jdbc:postgresql://localhost:5432/Study
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#server
server.servlet.context-path=/api/v1

 Oauth
 spring.security.oauth2.client.registration.github.client-id=Ov23liwkq90IopgC6b20
 spring.security.oauth2.client.registration.github.client-secret=af014b7bc4c6ab1ab7426f6c38051863f87a1f8f
